### ISSUE TITLE
Merge notifications together

### ISSUE THREAD

**Issue by oliviermaridat** [kanboard/plugin-rocketchat#3]
When I update a lot a Kanboard project, the related Rocket.chat channel is completely flooded. I know there were discussions about this in the past, but is there any way to improve this?

![kanboard-rocketchat](https://cloud.githubusercontent.com/assets/953989/22741970/6ba104b2-ee15-11e6-8b1e-2d0f4d91bd70.png)

If not, is there a way to let Rocket.chat "merge" all these notifications into one message (as it do when I filled a message and then enter a new one: my username appears only once).

**Comment by fguillot** [comment]
This improvement should probably go directly into the Kanboard code base because the problem is present for all notification types (Email, Slack, RocketChat, Mattermost...).

Some people propose to have a daily digest for email for example but I'm open to any suggestions. Another idea, Kanboard could stack up notifications in a SQL table and then send everything at once.

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
